[server]
maxUploadSize = 200

[theme]
primaryColor = "#32CD32"
backgroundColor = "#F5F2EB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F1F1F"
font = "sans serif"

[client]
showErrorDetails = "full"
